apiVersion: v1
kind: Service
metadata:
  name: {{ template "neo4j.fullname" . }}
  labels:
    neo4j.com/bolt: "true"
    neo4j.com/http: "true"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
{{- with .Values.service.labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  clusterIP: None
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
    - name: tcp-http
      port: 7474
      targetPort: 7474
    - name: tcp-bolt
      port: 7687
      targetPort: 7687
  selector:
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}